/*
-- Query: SELECT CONCAT('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(''', id, ''', ''', nome, ''', ', preco, ', ''', empresaId, ''', ''', descricao, ''', ', quantidadeEstoque, ');') 
FROM produto
LIMIT 0, 1000

-- Date: 2023-11-21 09:23
*/
INSERT INTO `` (`CONCAT('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(''', id, ''', ''', nome, ''', ', preco, ', ''', empresaId, ''', ''', descricao, ''', ', quantidadeEstoque, ');')`) VALUES ('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(\'1\', \'Perfume Feminino\', 50, \'1\', \'Fragrância floral suave\', 15);');
INSERT INTO `` (`CONCAT('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(''', id, ''', ''', nome, ''', ', preco, ', ''', empresaId, ''', ''', descricao, ''', ', quantidadeEstoque, ');')`) VALUES ('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(\'2\', \'Perfume Masculino\', 45, \'1\', \'Fragrância amadeirada intensa\', 12);');
INSERT INTO `` (`CONCAT('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(''', id, ''', ''', nome, ''', ', preco, ', ''', empresaId, ''', ''', descricao, ''', ', quantidadeEstoque, ');')`) VALUES ('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(\'3\', \'Batom Matte\', 15, \'1\', \'Batom de longa duração\', 25);');
INSERT INTO `` (`CONCAT('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(''', id, ''', ''', nome, ''', ', preco, ', ''', empresaId, ''', ''', descricao, ''', ', quantidadeEstoque, ');')`) VALUES ('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(\'4\', \'Base Líquida\', 30, \'1\', \'Base de longa duração\', 18);');
INSERT INTO `` (`CONCAT('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(''', id, ''', ''', nome, ''', ', preco, ', ''', empresaId, ''', ''', descricao, ''', ', quantidadeEstoque, ');')`) VALUES ('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(\'5\', \'Pó Compacto\', 18, \'1\', \'Pó para finalização da maquiagem\', 20);');
INSERT INTO `` (`CONCAT('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(''', id, ''', ''', nome, ''', ', preco, ', ''', empresaId, ''', ''', descricao, ''', ', quantidadeEstoque, ');')`) VALUES ('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(\'6\', \'Sombra em Pó\', 12, \'1\', \'Sombra altamente pigmentada\', 30);');
INSERT INTO `` (`CONCAT('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(''', id, ''', ''', nome, ''', ', preco, ', ''', empresaId, ''', ''', descricao, ''', ', quantidadeEstoque, ');')`) VALUES ('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(\'7\', \'Creme Anti-Idade\', 12, \'1\', \'Sombra altamente pigmentada\', 30);');
INSERT INTO `` (`CONCAT('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(''', id, ''', ''', nome, ''', ', preco, ', ''', empresaId, ''', ''', descricao, ''', ', quantidadeEstoque, ');')`) VALUES ('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(\'8\', \'Esmalte Duradouro\', 8, \'1\', \'Esmalte de longa duração\', 40);');
INSERT INTO `` (`CONCAT('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(''', id, ''', ''', nome, ''', ', preco, ', ''', empresaId, ''', ''', descricao, ''', ', quantidadeEstoque, ');')`) VALUES ('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(\'9\', \'Loção Corporal\', 20, \'1\', \'Hidratante corporal\', 25);');
INSERT INTO `` (`CONCAT('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(''', id, ''', ''', nome, ''', ', preco, ', ''', empresaId, ''', ''', descricao, ''', ', quantidadeEstoque, ');')`) VALUES ('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(\'10\', \'Creme para Mãos\', 10, \'1\', \'Hidratação intensa para as mãos\', 30);');
INSERT INTO `` (`CONCAT('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(''', id, ''', ''', nome, ''', ', preco, ', ''', empresaId, ''', ''', descricao, ''', ', quantidadeEstoque, ');')`) VALUES ('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(\'11\', \'Sabonete Facial\', 15, \'1\', \'Sabonete para limpeza facial\', 20);');
INSERT INTO `` (`CONCAT('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(''', id, ''', ''', nome, ''', ', preco, ', ''', empresaId, ''', ''', descricao, ''', ', quantidadeEstoque, ');')`) VALUES ('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(\'12\', \'Sabonete Líquido\', 12, \'1\', \'Sabonete líquido hidratante\', 25);');
INSERT INTO `` (`CONCAT('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(''', id, ''', ''', nome, ''', ', preco, ', ''', empresaId, ''', ''', descricao, ''', ', quantidadeEstoque, ');')`) VALUES ('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(\'13\', \'Gel de Limpeza\', 18, \'1\', \'Gel de limpeza facial\', 20);');
INSERT INTO `` (`CONCAT('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(''', id, ''', ''', nome, ''', ', preco, ', ''', empresaId, ''', ''', descricao, ''', ', quantidadeEstoque, ');')`) VALUES ('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(\'14\', \'Creme para os Olhos\', 25, \'1\', \'Creme para redução de olheiras\', 15);');
INSERT INTO `` (`CONCAT('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(''', id, ''', ''', nome, ''', ', preco, ', ''', empresaId, ''', ''', descricao, ''', ', quantidadeEstoque, ');')`) VALUES ('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(\'15\', \'Perfume Unissex\', 40, \'1\', \'Fragrância suave para ambos os sexos\', 10);');
INSERT INTO `` (`CONCAT('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(''', id, ''', ''', nome, ''', ', preco, ', ''', empresaId, ''', ''', descricao, ''', ', quantidadeEstoque, ');')`) VALUES ('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(\'16\', \'Kit Maquiagem Completo\', 80, \'1\', \'Paleta de maquiagem com diversos produtos\', 5);');
INSERT INTO `` (`CONCAT('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(''', id, ''', ''', nome, ''', ', preco, ', ''', empresaId, ''', ''', descricao, ''', ', quantidadeEstoque, ');')`) VALUES ('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(\'17\', \'Sérum Rejuvenescedor Radiante\', 89, \'1\', \'Ajuda a reduzir a aparência de linhas finas e promove um brilho natural\', 50);');
INSERT INTO `` (`CONCAT('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(''', id, ''', ''', nome, ''', ', preco, ', ''', empresaId, ''', ''', descricao, ''', ', quantidadeEstoque, ');')`) VALUES ('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(\'18\', \'Paleta de Sombras\', 65, \'1\', \'Paleta de sombras com longa duração e alta pigmentação\', 35);');
INSERT INTO `` (`CONCAT('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(''', id, ''', ''', nome, ''', ', preco, ', ''', empresaId, ''', ''', descricao, ''', ', quantidadeEstoque, ');')`) VALUES ('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(\'19\', \'Creme Revitalizante\', 120, \'1\', \'Creme para reduzir sinais de fadiga e restaurar a luminosidade natural\', 25);');
INSERT INTO `` (`CONCAT('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(''', id, ''', ''', nome, ''', ', preco, ', ''', empresaId, ''', ''', descricao, ''', ', quantidadeEstoque, ');')`) VALUES ('INSERT INTO produto(id, nome, preco, empresaId, descricao, quantidadeEstoque) VALUES(\'20\', \'Kit Pincéis Profissionais\', 99, \'1\', \'Conjunto de pincéis de alta qualidade para maquiagem profissional\', 40);');
