INSERT INTO servicosconsumidos(id, clienteId, servicoId) VALUES('1', '19', 1);
INSERT INTO servicosconsumidos(id, clienteId, servicoId) VALUES('2', '20', 2);
INSERT INTO servicosconsumidos(id, clienteId, servicoId) VALUES('3', '21', 3);
INSERT INTO servicosconsumidos(id, clienteId, servicoId) VALUES('4', '25', 2);
INSERT INTO servicosconsumidos(id, clienteId, servicoId) VALUES('5', '26', 3);
INSERT INTO servicosconsumidos(id, clienteId, servicoId) VALUES('6', '29', 1);
INSERT INTO servicosconsumidos(id, clienteId, servicoId) VALUES('7', '19', 3);
INSERT INTO servicosconsumidos(id, clienteId, servicoId) VALUES('8', '21', 2);
INSERT INTO servicosconsumidos(id, clienteId, servicoId) VALUES('9', '26', 2);
